quarkus.http.port=8082

quarkus.index-dependency.ruleset-contracts.group-id=br.com.cvc.poc
quarkus.index-dependency.ruleset-contracts.artifact-id=ruleset-contracts

engine.chunkSize=128
engine.parallelism=15
engine.useVirtualThreads=false
engine.audit.trace.enabled=false
engine.index.fields=Broker,Cidade,Estado,hotelId, Refundable, RoomType, CafeDaManha, qntdePax, Checkin, Checkout
engine.drl.compile-on-activation=false
engine.normalization.enabled=false

ruleset.storage.base-dir=${RULESET_STORAGE_BASE_DIR:../storage}

mp.messaging.incoming.ruleset_updates.connector=smallrye-kafka
mp.messaging.incoming.ruleset_updates.topic=ruleset_updates
mp.messaging.incoming.ruleset_updates.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.ruleset_updates.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.ruleset_updates.auto.offset.reset=earliest

kafka.bootstrap.servers=localhost:9092
