quarkus.http.port=8081

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/rulesdb

quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true

quarkus.index-dependency.ruleset-contracts.group-id=br.com.cvc.poc
quarkus.index-dependency.ruleset-contracts.artifact-id=ruleset-contracts

mp.messaging.outgoing.ruleset_updates.connector=smallrye-kafka
mp.messaging.outgoing.ruleset_updates.topic=ruleset_updates
mp.messaging.outgoing.ruleset_updates.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.ruleset_updates.value.serializer=org.apache.kafka.common.serialization.StringSerializer

kafka.bootstrap.servers=localhost:9092